version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "9001:9001"  # Expose the gRPC port
    networks:
      - grpc-network

  envoy:
    image: envoyproxy/envoy:v1.21.0
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9095:8080"  # Envoy HTTP listener
      - "9901:9901"  # Envoy admin interface
    depends_on:
      - backend
    networks:
      - grpc-network

  grpc-react:
    build: ./grpc-react
    ports:
      - "3000:3000"  # Expose the React app port
    depends_on:
      - envoy
    networks:
      - grpc-network

networks:
  grpc-network:
    driver: bridge